// const funcionQueMandaALlamarElCallback = ((error,valor) =>{
//     if(error){controla el error}
//     if(valor) {es porque todo sali√≥ bien}
// })